"""add gpt4 limits; add model_name

Revision ID: 1f755ce557ab
Revises: 
Create Date: 2023-03-15 19:08:33.390865

"""
from alembic import op
import sqlalchemy as sa

from api.enums import ChatModels

# revision identifiers, used by Alembic.
revision = '1f755ce557ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('model_name', sa.String(), nullable=True, comment='使用的模型'))
    op.drop_column('conversation', 'use_paid')
    op.add_column('user', sa.Column('can_use_gpt4', sa.Boolean(), default=False, server_default="0", nullable=False, comment='是否可以使用gpt4模型'))
    op.add_column('user', sa.Column('available_gpt4_ask_count', sa.Integer(), default=-1, server_default="-1", nullable=False, comment='可用的gpt4对话次数'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'available_gpt4_ask_count')
    op.drop_column('user', 'can_use_gpt4')
    op.drop_column('conversation', 'model_name')
    op.add_column('conversation', sa.Column('use_paid', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
