"""Add source_id for BaseConversation

Revision ID: 333722b0921e
Revises: 7d94b5503088
Create Date: 2024-02-03 12:29:17.095124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333722b0921e'
down_revision = '7d94b5503088'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('source_id', sa.String(length=256), nullable=True, comment='对话来源id'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'source_id')
    # ### end Alembic commands ###
