"""Add extra_info in UploadedFileInfo

Revision ID: 7d94b5503088
Revises: 0d790c2c26dc
Create Date: 2023-11-16 09:08:43.300383

"""
from alembic import op
import sqlalchemy as sa
from api.database.custom_types import Pydantic
from api.models.json import UploadedFileExtraInfo

# revision identifiers, used by Alembic.
revision = '7d94b5503088'
down_revision = '0d790c2c26dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_files', sa.Column('extra_info', Pydantic(UploadedFileExtraInfo), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploaded_files', 'extra_info')
    # ### end Alembic commands ###
