import { saveAs } from 'file-saver';

import { ChatMessage } from '@/types/custom';
import { RevConversationSchema } from '@/types/schema';
import { getModelNameTrans } from '@/utils/renders';

export const saveAsMarkdown = (conv: RevConversationSchema, messageList: ChatMessage[]) => {
  let content = `# ${conv.title}\n\n`;
  const create_time = new Date(conv.create_time ? conv.create_time + 'Z' : new Date()).toLocaleString();
  content += `Date: ${create_time}\nModel: ${getModelNameTrans(conv.model_name as any)}\n`;
  content += 'generated by [ChatGPT Web Share](https://github.com/moeakwak/chatgpt-web-share)\n\n';
  content += '---\n\n';
  let index = 0;
  for (const message of messageList) {
    if (message.author_role === 'user') {
      // 选取第一行作为标题，最多50个字符，如果有省略则加上...
      let title = message.message!.trim().split('\n')[0];
      if (title.length >= 50) {
        title = title.slice(0, 47) + '...';
      }
      content += `## ${++index}. ${title}\n\n`;
      content += `### User\n\n${message.message}\n\n`;
    } else {
      content += `### ChatGPT\n\n${message.message}\n\n`;
      content += '---\n\n';
    }
  }
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  saveAs(blob, `${conv.title} - ChatGPT history.md`);
};
